from werkzeug.security import generate_password_hash

# (name, category, icon, why, health_effects, warning_signs, detection, prevention, recommendations, [(adulterant, description)])
FOODS = [
 ("Milk", "Dairy", "🥛", "Water is added to increase volume, and other substances are added to hide the dilution and extend shelf life.",
  "Stomach upset and food poisoning are common. Long-term intake of chemical additives such as detergent or urea may strain the kidneys and liver.",
  "Very watery or bluish look; soapy feel or bitter taste; excessive foam when shaken; yellowish tinge after boiling.",
  "Awareness check: a drop on a slanted, smooth surface that runs fast with no trail may indicate dilution. A few drops of tincture iodine turning the sample blue suggest starch. Only lab tests confirm.",
  "Buy packaged milk from licensed dairies, check the seal and date, and boil before use.",
  "Refrigerate promptly, use within the stated date and report milk that smells or tastes unusual.",
  [("Water", "Added to increase volume."), ("Starch", "Added to thicken diluted milk."), ("Detergent", "Adds foam and a soapy feel."), ("Urea", "Mimics protein content in tests."), ("Neutralisers", "Soda or similar to mask sourness.")]),
 ("Honey", "Sweeteners", "🍯", "Cheaper sugar syrups are blended in to increase quantity and profit.",
  "Sugar syrups can spike blood sugar and offer none of honey's natural compounds. Chemical additives may upset digestion.",
  "Runs like thin syrup; crystallises unusually fast or never; very low price; overly sweet with no floral aroma.",
  "Awareness check: a spoon of pure honey tends to settle as a lump in water, while syrupy honey dissolves quickly. This is not conclusive.",
  "Choose brands with lab test reports and a licence number. Be cautious of very cheap honey.",
  "Store in a dry, closed glass jar at room temperature.",
  [("Sugar syrup", "Cane or invert sugar syrup."), ("Corn syrup", "High-fructose syrup blends."), ("Molasses/jaggery", "Used to fake colour and flavour.")]),
 ("Turmeric", "Spices", "🟡", "Bright colour signals quality, so cheap dyes and fillers are used to fake it.",
  "Some yellow dyes and lead-based colours are toxic and linked to nerve and organ damage with long exposure.",
  "Unnaturally bright yellow or orange colour; colour bleeds instantly into water; gritty or chalky feel.",
  "Awareness check: stir a pinch in water. Natural turmeric colours slowly and settles, while dyed powder streaks colour quickly. Not conclusive.",
  "Prefer whole turmeric roots and grind at home, or buy from certified brands.",
  "Store in airtight containers away from moisture and sunlight.",
  [("Metanil yellow", "Non-permitted textile dye."), ("Lead chromate", "Toxic colouring pigment."), ("Starch / chalk powder", "Bulking fillers.")]),
 ("Chilli powder", "Spices", "🌶️", "Colour and weight are increased with cheap coloured fillers.",
  "Non-permitted dyes are a concern for long-term health, and brick powder can harm the digestive tract.",
  "Gritty texture; colour streaks in water; unusually deep red; leaves stains on the fingers.",
  "Awareness check: sprinkle a little on water. Dyes leave coloured trails, and heavy fillers such as brick powder settle quickly. Not conclusive.",
  "Buy whole dried chillies and grind at home when possible.",
  "Buy small quantities from trusted sellers and store airtight.",
  [("Brick powder", "Adds weight and colour."), ("Sudan dyes", "Non-permitted synthetic dyes."), ("Sawdust", "Cheap bulking filler.")]),
 ("Coffee", "Beverages", "☕", "Cheaper roasted materials are mixed in to lower cost.",
  "Mostly quality loss, though unknown fillers can cause digestive discomfort.",
  "Grainy texture; sinks and colours the water quickly; weak aroma.",
  "Awareness check: sprinkle powder on water. Pure coffee tends to float longer, while fillers sink and leach colour faster. Coffee-chicory blends are legal when the label says so.",
  "Read labels for declared chicory percentages and choose whole beans.",
  "Store in airtight containers away from heat and moisture.",
  [("Chicory (undeclared)", "Roasted root mixed without labelling."), ("Tamarind seed powder", "Cheap roasted filler."), ("Roasted date seeds", "Used to bulk up powder.")]),
 ("Tea", "Beverages", "🍵", "Used leaves are recycled and colour is added to hide poor quality.",
  "Artificial colours and metal particles can irritate the stomach and are unsafe in the long run.",
  "Colour bleeds fast into water; uneven, dusty leaves; unusually dark liquor.",
  "Awareness check: press leaves on wet white paper. Coloured stains suggest added dye. A magnet passed over dry leaves can pick up iron filings.",
  "Buy from licensed brands and prefer loose leaf from known sellers.",
  "Keep in airtight tins away from strong smells.",
  [("Used tea leaves", "Dried and recoloured."), ("Artificial colours", "Added to fake strength."), ("Iron filings", "Added to increase weight.")]),
 ("Sugar", "Sweeteners", "🍚", "Cheap white powders and grit add weight.",
  "Mostly contamination concerns: grit and chemicals can irritate the stomach.",
  "Visible grit; cloudy solution; unusual smell.",
  "Awareness check: dissolve a spoon in a glass of water. Chalk or grit settles at the bottom and the water looks cloudy.",
  "Buy branded, sealed sugar.",
  "Store in dry, airtight containers.",
  [("Chalk powder", "Whitening filler."), ("Washing soda", "Non-food chemical."), ("Fine sand", "Adds weight.")]),
 ("Cooking oil", "Oils & Fats", "🛢️", "Cheaper or unsafe oils are mixed with premium oils.",
  "Some adulterants such as argemone oil have caused serious illness including swelling, breathing and heart problems.",
  "Unusual smell or taste; cloudiness; very low price; burning sensation after eating.",
  "Home checks are unreliable. Consumers should rely on sealed packs with FSSAI marks; only a laboratory can confirm oil purity.",
  "Avoid loose, unbranded oil; check the seal and batch details.",
  "Store away from heat and light, and never reuse oil many times.",
  [("Argemone oil", "Toxic seed oil."), ("Mineral oil", "Non-edible oil."), ("Cheaper blended oils", "Undeclared blending.")]),
 ("Ghee", "Oils & Fats", "🧈", "Cheaper fats and starchy fillers are mixed in to raise volume.",
  "Hydrogenated fats and unknown fillers can add unhealthy fat and digestive issues.",
  "Grainy or waxy texture; weak aroma; melts unevenly; low price.",
  "Awareness check: a few drops of iodine turning the sample blue indicate starch. Lab tests are needed for fat-mix confirmation.",
  "Buy from licensed dairies and check batch and expiry details.",
  "Store in a clean, dry, airtight jar.",
  [("Vanaspati", "Hydrogenated fat."), ("Animal fat", "Undeclared fats."), ("Mashed potato / starch", "Bulking filler.")]),
 ("Salt", "Essentials", "🧂", "White powders are mixed in to increase quantity.",
  "Non-food powders can upset digestion and reduce iodine benefits.",
  "Cloudy solution; visible residue; clumping; sticky or damp feel.",
  "Awareness check: dissolve in water. Pure salt gives a mostly clear solution, while chalk turns the water cloudy and settles.",
  "Choose iodised, sealed, branded salt.",
  "Keep in a dry container away from steam.",
  [("Chalk powder", "White bulking filler."), ("White stone powder", "Non-food filler."), ("Non-iodised salt sold as iodised", "Mislabelling.")]),
 ("Black pepper", "Spices", "⚫", "Similar-looking seeds are mixed in for weight and profit.",
  "Mostly quality and contamination concerns; mineral oil coating is unsafe for regular use.",
  "Lighter, shrivelled berries; shiny oily coating; weak aroma.",
  "Awareness check: drop into water. Papaya seeds tend to float while real pepper sinks. Not conclusive.",
  "Buy whole peppercorns and grind at home.",
  "Store airtight and away from light.",
  [("Papaya seeds", "Look similar to pepper."), ("Light berries", "Low-grade pepper."), ("Mineral oil", "Added for shine.")]),
 ("Wheat flour", "Grains & Pulses", "🌾", "Fillers and bleaching agents are used to add weight or improve looks.",
  "Grit and chemical additives can cause digestive issues and tooth damage.",
  "Gritty feel; unusually white; sour or musty smell; lumps.",
  "Awareness check: mix flour with water and a little lemon juice. Fizzing may suggest chalk. Not conclusive.",
  "Buy sealed flour with clear manufacturing dates.",
  "Store in airtight containers and use within a few months.",
  [("Chalk powder", "White filler."), ("Sand / grit", "Adds weight."), ("Excess bleaching agents", "Used to whiten.")]),
 ("Pulses", "Grains & Pulses", "🫘", "Cheaper look-alike pulses and colours are added.",
  "Kesari dal mixed in large amounts over time can cause nerve damage (lathyrism).",
  "Wedge-shaped grains; colour rubs off on wet hands; very shiny polish.",
  "Awareness check: rub grains on wet cloth. Colour transfer suggests added dye. Kesari dal has a distinctive wedge shape.",
  "Buy from licensed sellers and wash and soak before cooking.",
  "Store in airtight containers with dry conditions.",
  [("Kesari dal", "Harmful look-alike pulse."), ("Metanil yellow", "Dye for a fresh look."), ("Mineral oil polish", "Added for shine.")]),
 ("Sweets", "Sweets", "🍬", "Non-permitted colours and cheap fillers are used to make sweets look richer.",
  "Non-permitted dyes and unsafe foil can cause allergies and stomach trouble.",
  "Very bright, unnatural colours; sticky or off smell; grainy texture in milk sweets.",
  "Awareness check: real silver leaf burns to a shiny ball, while aluminium foil leaves grey ash. Only labs confirm dyes.",
  "Buy from licensed shops, and prefer fresh sweets over long-stored ones.",
  "Refrigerate milk-based sweets and finish within 1-2 days.",
  [("Artificial colours", "Non-permitted dyes."), ("Aluminium foil", "Sold as silver leaf."), ("Synthetic khoya", "Made without milk solids.")]),
]

ARTICLES = [
 ("What is food adulteration?", "Basics", "🔎", "Understanding how and why food is adulterated.",
  "Food adulteration means adding or removing substances so the food no longer matches its stated quality. It may be intentional for profit or accidental through poor handling. Common forms include dilution, substitution, colouring and mixing fillers."),
 ("Smart shopping checklist", "Buying tips", "🛒", "What to check before you pay.",
  "Check the FSSAI licence number, batch number and expiry date. Look for intact seals. Compare price with typical market price, since deals that look too good often are. Prefer whole spices and grains, and buy from trusted, licensed sellers."),
 ("Storing food safely", "Storage", "🧊", "Keep quality high and contamination low.",
  "Use airtight containers, keep them dry and away from sunlight, label dates, and follow first-in-first-out. Refrigerate dairy and cooked food promptly, and keep raw and cooked items separate."),
 ("Do's and Don'ts", "Do's & Don'ts", "✅", "Simple habits that reduce risk.",
  "Do read labels, wash produce, and report suspicious products. Don't buy loose, unlabelled oils, don't rely on looks alone, and don't consume food that smells or tastes unusual."),
 ("Home checks: helpful but limited", "Detection", "🧪", "Awareness tests are hints, not proof.",
  "Simple home checks can raise suspicion, but they cannot confirm adulteration. If you are concerned, stop using the product and report it. Certified laboratories provide definitive results."),
 ("Know your rights as a consumer", "Consumer rights", "⚖️", "Where to complain and what to expect.",
  "You can raise complaints with local food safety authorities. Keep the bill, pack and batch details. Photos and clear notes speed up investigations. Use this platform to record a report."),
]


def seed(conn):
    if not conn.execute("SELECT 1 FROM foods LIMIT 1").fetchone():
        for name, cat, icon, why, health, warn, detect, prevent, reco, adds in FOODS:
            cur = conn.execute(
                "INSERT INTO foods (name, category, icon, why, health_effects, warning_signs, detection, prevention, recommendations) VALUES (?,?,?,?,?,?,?,?,?)",
                (name, cat, icon, why, health, warn, detect, prevent, reco))
            conn.executemany("INSERT INTO adulterants (food_id, name, description) VALUES (?,?,?)",
                             [(cur.lastrowid, a, d) for a, d in adds])
    if not conn.execute("SELECT 1 FROM awareness_articles LIMIT 1").fetchone():
        conn.executemany("INSERT INTO awareness_articles (title, category, icon, summary, content) VALUES (?,?,?,?,?)", ARTICLES)
    if not conn.execute("SELECT 1 FROM admins LIMIT 1").fetchone():
        conn.execute("INSERT INTO admins (username, password_hash) VALUES (?, ?)", ("admin", generate_password_hash("Admin@123")))
    if not conn.execute("SELECT 1 FROM users LIMIT 1").fetchone():
        conn.execute("INSERT INTO users (full_name, email, phone, password_hash) VALUES (?,?,?,?)",
                     ("Demo User", "demo@foodsafe.com", "9876543210", generate_password_hash("Demo@1234")))
        conn.execute("INSERT INTO reports (report_code, user_id, product, brand, location, report_date, description, contact, status) VALUES (?,?,?,?,?,?,?,?,?)",
                     ("FAR-DEMO-0001", 1, "Turmeric powder", "Sample Brand", "Local market", "2026-09-01",
                      "Colour bled instantly in water and the powder felt gritty.", "9876543210", "pending"))
